### ISSUE TITLE
Combine minikube and ocp scripts

### ISSUE THREAD

**Issue by dejanb** [drogue-iot/drogue-cloud#10]

**Comment by lulf** [comment]
Just adding a note on this: it would be nice if resources can use Kubernetes-native resources as the base wherever it can. For instance, OCP  now supports Ingress resource, so it could potentially be a time-saver to reuse that for both Kubernetes and OCP. 

Also, making the script to work on any Kubernetes deployment (i.e. GKE, AKS or Digital ocean)  would be nice!

**Comment by dejanb** [comment]
@lulf Agree 100%. We should definitely strive to do that. I would also like us to be able to run against any cluster with knative already installed (OCP or any other).

**Comment by ctron** [comment]
> OCP now supports Ingress resource

Yes and no. Using ingress has two downsides:
a) It only can handle HTTP, and not TLS SNI
b) It doesn't work out of the box … you still need some manual setup with nodeports or loadbalancers

So I don't think using ingress for OCP has much benefit over routes.

**Comment by dejanb** [comment]
Closing this now. We can open new issues for further improvements.
