### ISSUE TITLE
Parsing error on device names with space on Sandbox

### ISSUE THREAD

**Issue by vedangj044** [drogue-iot/drogue-cloud#103]
While using the sandbox, when we try to view the details of the device, it works well, but it doesn't open when the device name has a space in it.
Here is a video to explain the situation.

https://user-images.githubusercontent.com/43697446/126173198-f40fe056-0d48-4245-a5c5-b8e1143a20de.mp4

**Comment by ctron** [comment]
Should be closed in 0.7! Thanks for reporting!
