### ISSUE TITLE
Support multi-tenant deployment

### ISSUE THREAD

**Issue by dejanb** [drogue-iot/drogue-cloud#12]
Currently everything is tied to `drogue-cloud` namespace

**Comment by lulf** [comment]
What sort of multitenancy is it that you are thinking of here? Http/mqtt endpoint per namespace mapping to different tenants?

**Comment by dejanb** [comment]
Yeah, I was thinking per namespace level.

**Comment by ctron** [comment]
I am not sure I would tie Kubernetes resources to the tenant.

Taking a look at this from an "as a service" perspective, I don't think it  matters where the stuff is running.

However I think we do need an endpoint (service, route) per tenant, to handle the X.509 client authentication.

I also think we should be able to run multiple installations on the same cluster from the start.

So my proposal would be:
* We ensure that we can run multiple installations (in different namespaces)
* One installation can handle multiple tenants (in the same namespace, but with dedicated endpoints, not necessarily dedicated deployments)

**Comment by ctron** [comment]
I removed the "to different namespaces" from the title in order to discuss this part in the design document I am preparing.

**Comment by ctron** [comment]
I think we have multi-tenancy already in 0.4 and 0.5. For 0.6 we need start working on splitting up the Kafka topic. I would close this issue. Please re-open if you disagree.

**Comment by ctron** [comment]
Follow up issue: #62
