### ISSUE TITLE
Console backend receives empty client secret on first start

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drogue-cloud#25]
When deploying the stack, the console-backend has an empty client secret at first:

~~~
CLIENT_ID=drogue
CLIENT_SECRET=
~~~

While the secret has the proper content:

~~~
data:
  CLIENT_ID: ZHJvZ3Vl
  CLIENT_SECRET: ZTc0ODM2Y2QtMGY3NS00ZDZkLWIzNDEtNDIyNDE5YjZjMTk3
~~~

I assume the keycloak operator updates the secret later on, so we must check this somehow.

**Comment by lulf** [comment]
Maybe a startup script in the console-backend pod that checks for non-empty contents and exits if not? Alternatively an init-container that waits until the content exists (to avoid the > 0 restarts)

**Comment by ctron** [comment]
> Alternatively an init-container that waits until the content exists (to avoid the > 0 restarts)

Cool idea!
