### ISSUE TITLE
Allow adding additional redirectUris to the SSO client configuration

### ISSUE THREAD

**Issue by lulf** [drogue-iot/drogue-cloud#293]
At present the "drogue" client in Keycloak infers the redirectUris based on the ingress configuration. For applications that integrate with the SSO outside the sandbox, it's necessary to add custom redirects for those applications. 

To fix that, the helm charts needs to expose a configuration option for adding additional redirect Uris for the SSO clients. This should be done once the Keycloak operator changes settles.

**Comment by ctron** [comment]
I am wondering if it would be sufficient to add a new keycloak client to the realm? Like we do it for Grafana and Ditto.

**Comment by ctron** [comment]
Part of the helm charts. But done for the next release.
