### ISSUE TITLE
server binary crashes when enabling frontend

### ISSUE THREAD

**Issue by jbtrystram** [drogue-iot/drogue-cloud#310]
```
[drogue-cloud] ./target/release/drogue-cloud-server run --enable-all --server-key key.pem --server-cert certificate.pem   --enable-console-frontend
Migrating database schema...
Migrating database schema... done!
Configuring keycloak... done!
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', server/src/main.rs:799:50
```

However this works, 
So it's just a bit of argument infering to do 
```
/target/release/drogue-cloud-server run --enable-all --server-key key.pem --server-cert certificate.pem --ui-dist console-frontend/dist
```

Side note : `enable-all`  do not enable the console frontend

**Comment by ctron** [comment]
> Side note : enable-all do not enable the console frontend

That is actually intentional, as it is not clear where the frontend files would be located.

However, it should not crash.

**Comment by jbtrystram** [comment]
Ok so then `--enable-console-frontend` and `--ui-dist` are redondant arguments. 
Because looking at the code : `--enable-console-frontend` needs `--ui-dist` to be set-up anyway. I suppose `ui-dist` was a latter addition. 
I'll open a PR
