### ISSUE TITLE
"make test" is broken

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drogue-cloud#35]
Originally "make test" used docker/podman to run the build and the tests.

However, the tests now start containers as well. So that means that we start containers inside of containers. Unfortunately that broke "make test". "make container-test" still works, but requires the user to have all kind of development tools installed, which can be tricky on windows and mac os.

**Comment by ctron** [comment]
For docker we can run docker-in-docker, by passing in the docker socket. This actually creates containers alongside the builder container (sibling containers), but still it works for our case.

For podman the story is different. Podman can run inside of podman. However, podman cannot run inside of docker. So it is either podman-in-podman or docker-in-docker. Mixing environments is not possible (e.g. podman-in-docker). As podman is only available for Linux, building solely on podman would exclude windows and mac developers.

Also, currently there seems to be no way to install `podman` inside of UBI8 images. Which rules out podman-in-podman anyway.

When PR #36 is merged, we still have the problem that people running podman, cannot run `make test`.

One idea would be to use `podman-remote`, which emulates a docker socket, that we could pass in the same way as with docker.  And would not require us to install "podman" inside of the UBI image.

**Comment by srisatya1197** [comment]
@ctron Hello Sir I want to contribute to this issue I'm noob into this Can you please elucidate me so that I can work on this issue

**Comment by ctron** [comment]
> @ctron Hello Sir I want to contribute to this issue I'm noob into this Can you please elucidate me so that I can work on this issue

Thank you for your interest in the project and this issue. However, I don't think this is a good first issue to work on.

**Comment by srisatya1197** [comment]
Ok Sir .Sir please don't mine for asking this query can you please suggest any good first issues or any issues I will learn about it

**Comment by ctron** [comment]
I am closing this one now. It still is an issue. But it doesn't seem to bother anyone too much, even myself. We can re-open if that should change.
