### ISSUE TITLE
Inconsistent use of dirname - hack | scripts 

### ISSUE THREAD

**Issue by vedangj044** [drogue-iot/drogue-cloud#47]
The release archive promote the use of `./scripts/drogue.sh` in the generated assets ( install-*.zip ) while the source code contains `./hack/drogue.sh` 
This may lead to inconsistency in documentation.

**Comment by ctron** [comment]
Thanks for the feedback. I agree, this is inconsistent. And even though "the book" has a section about that, I made the same mistake in the book :grin: 

I think the right approach here is to rename the folder in the repository into `scripts`. As having a `hack` folder in the installer archives seems odd as well.
