### ISSUE TITLE
Provide additional deployment model for a public cloud provider

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drogue-cloud#58]
We want to have at least one additional deployment for a public cloud provider.

The goal is not to use OpenShift and abstract away all the differences. The goal also is not host a bunch of additional deployments for all the different APIs and requirements.

But to see what changes are required for a specific Kubernetes variant like GKE, Azure, AWS, DigitalOcean, … and learn some things that might help generalize the deployment.

**Comment by ctron** [comment]
@lulf I know you had it running on GKE. Do you think we can close this for 0.6.0?

**Comment by lulf** [comment]
@ctron Agreed, I forgot to close the issue.
