### ISSUE TITLE
Proposal on making install script more appealing

### ISSUE THREAD

**Issue by lulf** [drogue-iot/drogue-cloud#76]
Just a thought I had regarding our discussion on scripts vs helm vs operator. This felt too small to be an RFC, so I just thought I'd start a discussion here. The idea is just to modify/rename drogue.sh, status.sh or wrapping them in a `drgadm` script. 

The `drgadm` script could just be drogue.sh renamed, wrap it, or combine it with helm or operator under the hood. I find it appealing that you don't really need to touch Kubernetes with such an interface. It would be similar to the `kubeadm` tool that exists for installing and managing Kubernetes clusters, in the same way `drg` is similar to `kubectl`.

```
drgadm install -c kubernetes # Does whatever drogue.sh does
drgadm status # Invokes status.sh
```

Maybe the first step could be just to refactor the drogue.sh and status.sh into functions that can be sourced and invoked from this tool?

Where this ties into helm I'm not sure, but if it uses helm, we introduce a dependency other than kubectl. Maybe helm would just be separate to this, I'm not sure.

**Comment by ctron** [comment]
Yea, I like the idea of having a single entry-point. We have a hand full of scripts, and it "works just fine for me". But I am not sure how that would work over time.

**Comment by ctron** [comment]
I think it should be more appealing now. Both from an internal structure and from a user's perspective.

**Comment by lulf** [comment]
Agreed, I like the new scripts.
