### ISSUE TITLE
Allow using QoS 1 with the MQTT Integration

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drogue-cloud#95]

**Comment by JulianFeinauer** [comment]
If I understand QoS 1 right we need to send a PubAck Packet back to the sender as soon as we got the confirmation from Kafka that the Message was accepted, right?

**Comment by ctron** [comment]
Actually the title is a bit vague :) … We need to do this for both directions, events (to the consumer) and commands (from consumer, sounds weird).

For commands, yes: once kafka has ACKed the publish, there should be a PubAck sent back.

For events, we need to manually commit once we received the PubAck. Maybe this can serve as a blueprint: https://github.com/fede1024/rust-rdkafka/blob/master/examples/at_least_once.rs

**Comment by JulianFeinauer** [comment]
Hm... isnt it the other way round?
An event which is passed via the MQTT Endpoint should be forwarded to Kafka and then we have to return an PubAck (L187 in session/mod.rs I would assume).

But you are right, if someone uses the MQTT Consumption "Endpoint" then we have to have a logic which timeouts or retries deliveries from Kafka if we dont get a PubAck (we probably have to lock that up in the spec).

I personally would split that into two issues (as its totally unrelated code and probably also unrelated use cases) and would first go with the "events" thing which is easier as well as more relevant for many use cases.

WDYT @ctron ?
